apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: rack-1-ippool
spec:
  cidr: 10.244.0.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: rack == "1"
---
apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: rack-2-ippool
spec:
  cidr: 10.244.1.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: rack == "2"